  CREATE TABLE QUERY_HISTORY
   (	
		PROJECT_PREFIX VARCHAR2(3) NOT NULL ENABLE,
		QUERY_TEXT VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
		QUERY_COMMENT VARCHAR2(4000 BYTE) NOT NULL ENABLE,
		QUERY_TIME NUMBER NOT NULL ENABLE
	);