
  CREATE TABLE "HURTOWNIE"."MAIN_PROJECTS" 
   (	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PREFIX" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "MAIN_PROJECTS_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255;