  CREATE SEQUENCE query_id;
  
  CREATE TABLE QUERY_HISTORY
   (	
		ID_QUERY NUMBER NOT NULL,
		PROJECT_PREFIX VARCHAR2(3) NOT NULL ENABLE,
		QUERY_TEXT VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
		QUERY_COMMENT VARCHAR2(4000 BYTE) NOT NULL ENABLE,
		QUERY_TIME NUMBER NOT NULL ENABLE
	);
	
	CREATE TRIGGER query_log_id 
BEFORE INSERT ON query_history 
FOR EACH ROW
BEGIN
  SELECT query_id.NEXTVAL
  INTO   :new.id_query
  FROM   dual;
END;