CREATE TABLE TES_DIMENSION_ROOM 
   (	
		ID NUMBER, 
		ROOMNUMBER NUMBER, 
		PRIMARY KEY (ID)
	)
	
/
	 
CREATE TABLE TES_DIMENSION_TIME 
	(	
		ID NUMBER, 
		TIMET TIMESTAMP (6), 
		PRIMARY KEY (ID)
	)
	
/

CREATE TABLE TES_FACT_ENERGY 
   (	
		ID NUMBER, 
		ID_TIME NUMBER, 
		ID_ROOM NUMBER, 
		MEASUREVALUE NUMBER, 
		PRIMARY KEY (ID)
  
	 CONSTRAINT ENERGY_TIME_TIME_ID FOREIGN KEY (ID_TIME)
	  REFERENCES TES_DIMENSION_TIME (ID) ENABLE, 
	 CONSTRAINT ENERGY_ROOM_ROOM_ID FOREIGN KEY (ID_ROOM)
	  REFERENCES TES_DIMENSION_ROOM (ID) ENABLE
   ) 